BackendServer/src/app.module.ts, WebFrontend/package-lock.json, WebFrontend/src/routes/AppRouter.tsx
=> update: complete update

BackendServer/src/chat/chat.controller.ts, BackendServer/src/chat/chat.gateway.ts, BackendServer/src/chat/chat.service.ts, WebFrontend/src/pages/chat/ChatListPage.tsx, WebFrontend/src/pages/chat/ChatRoomPage.tsx
- [채팅방 나가기 기능 ] 
- [ 나갔다 들어온 시점 부터 수신한 메시지만 보기] 
- [ 버그: 1:1 대화방 나간 후 재생성 불가능 버그 해결]
=> feat: 채팅방 나가기, 입장 시간 이후 메시지 보기

BackendServer/src/chat/chat.service.ts
- [나가기 버튼을 누르면 참여 인원을 확인하여 0인 방이 생기면 관련된 데이터들을 데이터베이스 내에서 삭제 ]
=> Feat: 채팅방 관련 데이터 베이스 정리

WebFrontend/package-lock.json, WebFrontend/package.json, WebFrontend/src/pages/chat/ChatListPage.tsx, WebFrontend/src/pages/chat/ChatRoomPage.tsx, WebFrontend/src/utils/dateUtils.ts
- [채팅방 나가기 및 사용자 초대 기능 (채팅방목록 -> 채팅방내부) ] 
- [ 메시지 출력 시간 한국시간으로 포맷화]
=> Feat: chat-develop

BackendServer/package-lock.json, BackendServer/package.json, BackendServer/src/app.module.ts, BackendServer/src/auth/auth.module.ts, BackendServer/src/auth/user/dto/password.dto.ts, BackendServer/src/auth/user/password.controller.ts, BackendServer/src/auth/user/password.service.ts, BackendServer/src/auth/user/user.service.ts
- [이메일 인증번호 발송 및 검증 기능 ] 
- [ 비밀번호 찾기]
=> feat: updatePassword By gmail smtp

WebFrontend/src/pages/auth/ForgotPasswordPage.tsx
=> fix: modified_page

VideoEditorApp/ios/Podfile.lock, VideoEditorApp/package-lock.json, VideoEditorApp/package.json, VideoEditorApp/src/components/Common/SectionHeader.tsx, VideoEditorApp/src/components/Editor/RangeControl.tsx, VideoEditorApp/src/screens/HomeScreen.tsx, VideoEditorApp/src/screens/VideoEditScreen.arm.tsx, VideoEditorApp/src/screens/VideoEditScreen.tsx, VideoEditorApp/src/screens/WebScreen.tsx, VideoEditorApp/src/types.ts
1. 웹 컴포넌트와 앱 컴포넌트 사이를 왔다 갔다 해보세요.
=> feat: 웹에서 앱으로 토큰 넘겨주고 받는 기능 구현

WebFrontend/package-lock.json, WebFrontend/package.json, WebFrontend/src/components/atoms/avatar/Avatar.tsx, WebFrontend/src/components/atoms/button/PrimaryButton.tsx, WebFrontend/src/components/atoms/button/SecondaryButton.tsx, WebFrontend/src/components/atoms/icon/Icon.tsx, WebFrontend/src/components/atoms/input/TextInput.tsx, WebFrontend/src/components/atoms/modal/Modal.tsx, WebFrontend/src/components/molecules/MessageBubble.tsx, WebFrontend/src/components/molecules/MessageInput.tsx, WebFrontend/src/index.css, WebFrontend/src/pages/chat/ChatRoomPage.tsx, WebFrontend/src/routes/AppRouter.tsx, WebFrontend/src/routes/ProtectedRoute.tsx, WebFrontend/src/stores/chatStore.ts
Closes #
1. 여러가지 눌러보시면서 테스트 하시면 됩니다
2. 헤더부분 리스너 프로필 페이지 이동가능
3. 친구추가 카드섹션
4. 나가기 카드섹션
5. 푸터 채팅바 텍스트 에리아 확인
6. 페이지 왼쪽 스와이프 -> 시간 확인 
7. 
8.
=> feat: atom, molcule 컴포넌트 분리 및 생성, 채팅방 기능 구현 및 라우터 설정

BackendServer/src/used_product/used-product.service.ts, WebFrontend/src/components/layout/pages/practiceRoom/PracticeRoomDetailForm.tsx, WebFrontend/src/components/layout/pages/practiceRoom/PracticeRoomForm.tsx, WebFrontend/src/components/layout/pages/usedProduct/ProductForm.tsx, WebFrontend/src/pages/practiceRoom/CreatePracticeRoomPage.tsx, WebFrontend/src/pages/practiceRoom/PracticeRoomDetailPage.tsx, WebFrontend/src/pages/practiceRoom/UpdatePracticeRoomPage.tsx, WebFrontend/src/pages/usedProduct/CreateUsedProductPage.tsx, WebFrontend/src/pages/usedProduct/UpdateUsedProductPage.tsx, WebFrontend/src/types/practiceRoom.ts
=> fix: 합주실 게시판 FE 컴포넌트 분리

VideoEditorApp/ios/Podfile.lock, VideoEditorApp/ios/VideoEditorApp.xcodeproj/project.pbxproj, VideoEditorApp/package-lock.json, VideoEditorApp/package.json, VideoEditorApp/src/api/axiosInstance.ts, VideoEditorApp/src/screens/VideoEditScreen.tsx, VideoEditorApp/src/screens/WebScreen.tsx
#주의
아키텍쳐(x86)이슈로 잠시 ffmpeg기능을 주석처리했습니다. 영상 편집이나 인코딩 없이 바로 업로드 됩니다.
1. RN편집기에서 업로드
2. 마이페이지 확인
3. VINYL 확인
=> feat:하나의 동영상 처리 구현 완료(FFmpeg(X))

BackendServer/src/chat/chat.gateway.ts, BackendServer/src/chat/chat.service.ts, WebFrontend/src/App.tsx, WebFrontend/src/pages/chat/ChatListPage.tsx, WebFrontend/src/pages/chat/ChatRoomPage.tsx, WebFrontend/src/stores/chatStore.ts, WebFrontend/src/utils/dateUtils.ts
=> [fix]: 채팅 버그 수정

WebFrontend/src/components/map/LocationSaveHandler.tsx
=> fix: hot fix location error

WebFrontend/src/components/molecules/user/UserSearch.tsx, WebFrontend/src/components/organisms/SearchOverlay.tsx, WebFrontend/src/pages/user/UserPage.tsx
=> Feat: 유저페이지 검색 기능 추가

BackendServer/src/config/aws-config.service.ts, BackendServer/src/video-insert/video-insert.service.ts, BackendServer/src/videos/videos.service.ts
=> update: switch s3 to ssm client for server

VideoEditorApp/src/components/Common/CommonButton.tsx, VideoEditorApp/src/components/Editor/GlobalControls.tsx, VideoEditorApp/src/components/Editor/PreviewPanel.tsx, VideoEditorApp/src/components/Editor/Timeline.tsx, VideoEditorApp/src/hooks/useVideoProcessor.ts, VideoEditorApp/src/screens/VideoEditScreen.tsx
=> Feature/video edit UI

BackendServer/src/chat/chat.controller.ts, BackendServer/src/chat/chat.service.ts, WebFrontend/src/pages/chat/ChatRoomPage.tsx
=> fix: chat-module

BackendServer/src/config/config.controller.ts, WebFrontend/src/pages/auth/LoginPage.tsx, WebFrontend/src/stores/useConfigStore.ts
=> fix: kakao login

BackendServer/src/chat/chat.gateway.ts, BackendServer/src/main.ts
=> update: update cors

WebFrontend/src/components/layout/pages/practiceRoom/PracticeRoomDetailForm.tsx
=> fix: add type function on complete

BackendServer/src/chat/chat.gateway.ts
=> fix: gate test

BackendServer/src/chat/chat.gateway.ts
=> fix: temp fix cors

VideoEditorApp/src/components/Editor/PreviewPanel.tsx, VideoEditorApp/src/components/Editor/Timeline.tsx, VideoEditorApp/src/env.d.ts, VideoEditorApp/src/hooks/useVideoProcessor.ts, VideoEditorApp/src/screens/VideoEditScreen.tsx
=> feat: 데이터 송출 용 조건 분기 설정

BackendServer/src/auth/kakao.strategy.ts, BackendServer/src/auth/user/user.controller.ts, WebFrontend/src/pages/auth/RegisterPage.tsx, WebFrontend/src/pages/user/UserPage.tsx
=> Feat: unique user

WebFrontend/src/pages/user/UserPage.tsx
=> fix: 존재하지 않는 유저 검색 에러 핸들링

BackendServer/src/app.module.ts, BackendServer/src/auth/user/password.service.ts
=> fix: 이메일 인증모듈 수정

VideoEditorApp/ios/VideoEditorApp.xcodeproj/project.pbxproj, VideoEditorApp/src/navigation/AppNavigator.tsx, VideoEditorApp/src/navigation/types.ts, VideoEditorApp/src/screens/RecordScreen.tsx, VideoEditorApp/src/screens/WebScreen.tsx
=> feat: 합주 + 녹화 재 구현

BackendServer/src/ensemble/dto/create-recruit-ensemble.dto.ts
=> fix: tmp fix date to string

BackendServer/.gitignore, VideoEditorApp/android/app/build.gradle, VideoEditorApp/android/build.gradle, VideoEditorApp/package-lock.json
=> update: update for release

WebFrontend/src/components/organisms/vinyl/VinylContents.tsx, WebFrontend/src/pages/vinyl/VinylPage.tsx
=> feat: 무한스크롤 구현

WebFrontend/src/pages/community/CommunityFeedPage.tsx
=> fix: wrong import name in CommunityFeedPage

WebFrontend/src/components/atoms/input/MessageInput.tsx, WebFrontend/src/components/organisms/community/CommunityFeed.tsx, WebFrontend/src/pages/community/CategoryPostListPage.tsx
=> feat: 좋아요 색 바꾸기

WebFrontend/src/pages/vinyl/VinylPage.tsx
=> fix: 안드로이드 드래그 이벤트 해결

WebFrontend/src/pages/community/PostDetailPage.tsx
=> refactor: replace dangerouslySetInnerHTML tag to pre
